### ISSUE TITLE
Specify dependencies

### ISSUE THREAD

**Issue by luisaforozco** [MALES-project/SpeckleCn2Profiler#27]
Let's define the requirements in `pyproject.toml` and `requirements.txt`.
Also we can use something like [generate_requirements_txt.py](https://github.com/GEMDAT-repos/GEMDAT/blob/main/tools/generate_requirements_txt.py) to auto-generate `requirements.txt`.
We can then remove the `pipreqs` action in `test.yaml`.

**Comment by SCiarella** [comment]
as a workaround for `lie_learn` problem, one could add `cython` to the requirements and drop support to python3.11

**Comment by SCiarella** [comment]
`pyproject.toml` has been implemented and the problem of stale dependencies has been solved by using `dependencies = [  'lie_learn @ git+https://github.com/AMLab-Amsterdam/lie_learn', ...` to use the github version instead of the pypi.

`requirements.txt ` are now generated by the publishing action.
